[package]
org= "ballerinax"
name= "microsoft.teams"
version= "0.1.1-SNAPSHOT"
authors = ["Ballerina"]
keywords = ["communication/team chat", "cost/paid", "vendor/microsoft"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.teams"
license = ["Apache-2.0"]

[build-options]
observability-included=true

