[package]
org= "ballerinax"
name= "microsoft.teams"
version= "0.1.1-SNAPSHOT"
authors = ["Ballerina"]
keywords = ["microsoft", "teams", "communication"]
repository = "https://github.com/ballerina-platform/module-ballerinax-microsoft.teams"
license = ["Apache-2.0"]

[build-options]
observability-included=true

